# Site settings
title: 'Efe Gürkan YALAMAN'
description: 'Human being with an engineering degree. Graduated from Ege
  University. Frontend Software Engineer at Linovi. Loves C++. Free Software
  Enthusiast. ♥ Izmir.'
url: 'efegurkan.github.io'
baseurl: '/'
google_analytics: 'UA-72808756-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Efe Gürkan YALAMAN'
  email: efeyalaman@gmail.com
  twitter_username: efegurkan
  github_username: efegurkan
  linkedin_username: efegurkanyalaman

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
